/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoucherRouteImport } from './routes/voucher'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as KeranjangRouteImport } from './routes/keranjang'
import { Route as KatalogRouteImport } from './routes/katalog'
import { Route as FlashSaleRouteImport } from './routes/flash-sale'
import { Route as FaviconDoticoRouteImport } from './routes/favicon[.]ico'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdukSlugRouteImport } from './routes/produk.$slug'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/_admin/route'
import { Route as AuthenticatedAkunWishlistRouteImport } from './routes/_authenticated/akun/wishlist'
import { Route as AuthenticatedAkunPesananIndexRouteImport } from './routes/_authenticated/akun/pesanan/index'
import { Route as AuthenticatedAdminAdminIndexRouteImport } from './routes/_authenticated/_admin/admin/index'
import { Route as AuthenticatedAkunPesananIdRouteImport } from './routes/_authenticated/akun/pesanan/$id'
import { Route as AuthenticatedAdminAdminVoucherRouteImport } from './routes/_authenticated/_admin/admin/voucher'
import { Route as AuthenticatedAdminAdminProdukRouteImport } from './routes/_authenticated/_admin/admin/produk'
import { Route as AuthenticatedAdminAdminPesananRouteImport } from './routes/_authenticated/_admin/admin/pesanan'
import { Route as AuthenticatedAdminAdminPengaturanRouteImport } from './routes/_authenticated/_admin/admin/pengaturan'
import { Route as AuthenticatedAdminAdminPelangganRouteImport } from './routes/_authenticated/_admin/admin/pelanggan'
import { Route as AuthenticatedAdminAdminAuditRouteImport } from './routes/_authenticated/_admin/admin/audit'
import { Route as AuthenticatedAdminAdminPromosiTemaRouteImport } from './routes/_authenticated/_admin/admin/promosi.tema'
import { Route as AuthenticatedAdminAdminPromosiFlashSaleRouteImport } from './routes/_authenticated/_admin/admin/promosi.flash-sale'
import { Route as AuthenticatedAdminAdminPromosiDashboardRouteImport } from './routes/_authenticated/_admin/admin/promosi.dashboard'
import { Route as AuthenticatedAdminAdminPromosiAdsRouteImport } from './routes/_authenticated/_admin/admin/promosi.ads'

const VoucherRoute = VoucherRouteImport.update({
  id: '/voucher',
  path: '/voucher',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const KeranjangRoute = KeranjangRouteImport.update({
  id: '/keranjang',
  path: '/keranjang',
  getParentRoute: () => rootRouteImport,
} as any)
const KatalogRoute = KatalogRouteImport.update({
  id: '/katalog',
  path: '/katalog',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashSaleRoute = FlashSaleRouteImport.update({
  id: '/flash-sale',
  path: '/flash-sale',
  getParentRoute: () => rootRouteImport,
} as any)
const FaviconDoticoRoute = FaviconDoticoRouteImport.update({
  id: '/favicon.ico',
  path: '/favicon.ico',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukSlugRoute = ProdukSlugRouteImport.update({
  id: '/produk/$slug',
  path: '/produk/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAkunWishlistRoute =
  AuthenticatedAkunWishlistRouteImport.update({
    id: '/akun/wishlist',
    path: '/akun/wishlist',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAkunPesananIndexRoute =
  AuthenticatedAkunPesananIndexRouteImport.update({
    id: '/akun/pesanan/',
    path: '/akun/pesanan/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAdminIndexRoute =
  AuthenticatedAdminAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAkunPesananIdRoute =
  AuthenticatedAkunPesananIdRouteImport.update({
    id: '/akun/pesanan/$id',
    path: '/akun/pesanan/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAdminVoucherRoute =
  AuthenticatedAdminAdminVoucherRouteImport.update({
    id: '/admin/voucher',
    path: '/admin/voucher',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminProdukRoute =
  AuthenticatedAdminAdminProdukRouteImport.update({
    id: '/admin/produk',
    path: '/admin/produk',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminPesananRoute =
  AuthenticatedAdminAdminPesananRouteImport.update({
    id: '/admin/pesanan',
    path: '/admin/pesanan',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminPengaturanRoute =
  AuthenticatedAdminAdminPengaturanRouteImport.update({
    id: '/admin/pengaturan',
    path: '/admin/pengaturan',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminPelangganRoute =
  AuthenticatedAdminAdminPelangganRouteImport.update({
    id: '/admin/pelanggan',
    path: '/admin/pelanggan',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminAuditRoute =
  AuthenticatedAdminAdminAuditRouteImport.update({
    id: '/admin/audit',
    path: '/admin/audit',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminPromosiTemaRoute =
  AuthenticatedAdminAdminPromosiTemaRouteImport.update({
    id: '/admin/promosi/tema',
    path: '/admin/promosi/tema',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminPromosiFlashSaleRoute =
  AuthenticatedAdminAdminPromosiFlashSaleRouteImport.update({
    id: '/admin/promosi/flash-sale',
    path: '/admin/promosi/flash-sale',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminPromosiDashboardRoute =
  AuthenticatedAdminAdminPromosiDashboardRouteImport.update({
    id: '/admin/promosi/dashboard',
    path: '/admin/promosi/dashboard',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminPromosiAdsRoute =
  AuthenticatedAdminAdminPromosiAdsRouteImport.update({
    id: '/admin/promosi/ads',
    path: '/admin/promosi/ads',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/favicon.ico': typeof FaviconDoticoRoute
  '/flash-sale': typeof FlashSaleRoute
  '/katalog': typeof KatalogRoute
  '/keranjang': typeof KeranjangRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/voucher': typeof VoucherRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/akun/wishlist': typeof AuthenticatedAkunWishlistRoute
  '/admin/audit': typeof AuthenticatedAdminAdminAuditRoute
  '/admin/pelanggan': typeof AuthenticatedAdminAdminPelangganRoute
  '/admin/pengaturan': typeof AuthenticatedAdminAdminPengaturanRoute
  '/admin/pesanan': typeof AuthenticatedAdminAdminPesananRoute
  '/admin/produk': typeof AuthenticatedAdminAdminProdukRoute
  '/admin/voucher': typeof AuthenticatedAdminAdminVoucherRoute
  '/akun/pesanan/$id': typeof AuthenticatedAkunPesananIdRoute
  '/admin/': typeof AuthenticatedAdminAdminIndexRoute
  '/akun/pesanan/': typeof AuthenticatedAkunPesananIndexRoute
  '/admin/promosi/ads': typeof AuthenticatedAdminAdminPromosiAdsRoute
  '/admin/promosi/dashboard': typeof AuthenticatedAdminAdminPromosiDashboardRoute
  '/admin/promosi/flash-sale': typeof AuthenticatedAdminAdminPromosiFlashSaleRoute
  '/admin/promosi/tema': typeof AuthenticatedAdminAdminPromosiTemaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/favicon.ico': typeof FaviconDoticoRoute
  '/flash-sale': typeof FlashSaleRoute
  '/katalog': typeof KatalogRoute
  '/keranjang': typeof KeranjangRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/voucher': typeof VoucherRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/akun/wishlist': typeof AuthenticatedAkunWishlistRoute
  '/admin/audit': typeof AuthenticatedAdminAdminAuditRoute
  '/admin/pelanggan': typeof AuthenticatedAdminAdminPelangganRoute
  '/admin/pengaturan': typeof AuthenticatedAdminAdminPengaturanRoute
  '/admin/pesanan': typeof AuthenticatedAdminAdminPesananRoute
  '/admin/produk': typeof AuthenticatedAdminAdminProdukRoute
  '/admin/voucher': typeof AuthenticatedAdminAdminVoucherRoute
  '/akun/pesanan/$id': typeof AuthenticatedAkunPesananIdRoute
  '/admin': typeof AuthenticatedAdminAdminIndexRoute
  '/akun/pesanan': typeof AuthenticatedAkunPesananIndexRoute
  '/admin/promosi/ads': typeof AuthenticatedAdminAdminPromosiAdsRoute
  '/admin/promosi/dashboard': typeof AuthenticatedAdminAdminPromosiDashboardRoute
  '/admin/promosi/flash-sale': typeof AuthenticatedAdminAdminPromosiFlashSaleRoute
  '/admin/promosi/tema': typeof AuthenticatedAdminAdminPromosiTemaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/favicon.ico': typeof FaviconDoticoRoute
  '/flash-sale': typeof FlashSaleRoute
  '/katalog': typeof KatalogRoute
  '/keranjang': typeof KeranjangRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/voucher': typeof VoucherRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/produk/$slug': typeof ProdukSlugRoute
  '/_authenticated/akun/wishlist': typeof AuthenticatedAkunWishlistRoute
  '/_authenticated/_admin/admin/audit': typeof AuthenticatedAdminAdminAuditRoute
  '/_authenticated/_admin/admin/pelanggan': typeof AuthenticatedAdminAdminPelangganRoute
  '/_authenticated/_admin/admin/pengaturan': typeof AuthenticatedAdminAdminPengaturanRoute
  '/_authenticated/_admin/admin/pesanan': typeof AuthenticatedAdminAdminPesananRoute
  '/_authenticated/_admin/admin/produk': typeof AuthenticatedAdminAdminProdukRoute
  '/_authenticated/_admin/admin/voucher': typeof AuthenticatedAdminAdminVoucherRoute
  '/_authenticated/akun/pesanan/$id': typeof AuthenticatedAkunPesananIdRoute
  '/_authenticated/_admin/admin/': typeof AuthenticatedAdminAdminIndexRoute
  '/_authenticated/akun/pesanan/': typeof AuthenticatedAkunPesananIndexRoute
  '/_authenticated/_admin/admin/promosi/ads': typeof AuthenticatedAdminAdminPromosiAdsRoute
  '/_authenticated/_admin/admin/promosi/dashboard': typeof AuthenticatedAdminAdminPromosiDashboardRoute
  '/_authenticated/_admin/admin/promosi/flash-sale': typeof AuthenticatedAdminAdminPromosiFlashSaleRoute
  '/_authenticated/_admin/admin/promosi/tema': typeof AuthenticatedAdminAdminPromosiTemaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/checkout'
    | '/favicon.ico'
    | '/flash-sale'
    | '/katalog'
    | '/keranjang'
    | '/reset-password'
    | '/sitemap.xml'
    | '/voucher'
    | '/produk/$slug'
    | '/akun/wishlist'
    | '/admin/audit'
    | '/admin/pelanggan'
    | '/admin/pengaturan'
    | '/admin/pesanan'
    | '/admin/produk'
    | '/admin/voucher'
    | '/akun/pesanan/$id'
    | '/admin/'
    | '/akun/pesanan/'
    | '/admin/promosi/ads'
    | '/admin/promosi/dashboard'
    | '/admin/promosi/flash-sale'
    | '/admin/promosi/tema'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/checkout'
    | '/favicon.ico'
    | '/flash-sale'
    | '/katalog'
    | '/keranjang'
    | '/reset-password'
    | '/sitemap.xml'
    | '/voucher'
    | '/produk/$slug'
    | '/akun/wishlist'
    | '/admin/audit'
    | '/admin/pelanggan'
    | '/admin/pengaturan'
    | '/admin/pesanan'
    | '/admin/produk'
    | '/admin/voucher'
    | '/akun/pesanan/$id'
    | '/admin'
    | '/akun/pesanan'
    | '/admin/promosi/ads'
    | '/admin/promosi/dashboard'
    | '/admin/promosi/flash-sale'
    | '/admin/promosi/tema'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/checkout'
    | '/favicon.ico'
    | '/flash-sale'
    | '/katalog'
    | '/keranjang'
    | '/reset-password'
    | '/sitemap.xml'
    | '/voucher'
    | '/_authenticated/_admin'
    | '/produk/$slug'
    | '/_authenticated/akun/wishlist'
    | '/_authenticated/_admin/admin/audit'
    | '/_authenticated/_admin/admin/pelanggan'
    | '/_authenticated/_admin/admin/pengaturan'
    | '/_authenticated/_admin/admin/pesanan'
    | '/_authenticated/_admin/admin/produk'
    | '/_authenticated/_admin/admin/voucher'
    | '/_authenticated/akun/pesanan/$id'
    | '/_authenticated/_admin/admin/'
    | '/_authenticated/akun/pesanan/'
    | '/_authenticated/_admin/admin/promosi/ads'
    | '/_authenticated/_admin/admin/promosi/dashboard'
    | '/_authenticated/_admin/admin/promosi/flash-sale'
    | '/_authenticated/_admin/admin/promosi/tema'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRoute
  FaviconDoticoRoute: typeof FaviconDoticoRoute
  FlashSaleRoute: typeof FlashSaleRoute
  KatalogRoute: typeof KatalogRoute
  KeranjangRoute: typeof KeranjangRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VoucherRoute: typeof VoucherRoute
  ProdukSlugRoute: typeof ProdukSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voucher': {
      id: '/voucher'
      path: '/voucher'
      fullPath: '/voucher'
      preLoaderRoute: typeof VoucherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keranjang': {
      id: '/keranjang'
      path: '/keranjang'
      fullPath: '/keranjang'
      preLoaderRoute: typeof KeranjangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katalog': {
      id: '/katalog'
      path: '/katalog'
      fullPath: '/katalog'
      preLoaderRoute: typeof KatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flash-sale': {
      id: '/flash-sale'
      path: '/flash-sale'
      fullPath: '/flash-sale'
      preLoaderRoute: typeof FlashSaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favicon.ico': {
      id: '/favicon.ico'
      path: '/favicon.ico'
      fullPath: '/favicon.ico'
      preLoaderRoute: typeof FaviconDoticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/$slug': {
      id: '/produk/$slug'
      path: '/produk/$slug'
      fullPath: '/produk/$slug'
      preLoaderRoute: typeof ProdukSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/akun/wishlist': {
      id: '/_authenticated/akun/wishlist'
      path: '/akun/wishlist'
      fullPath: '/akun/wishlist'
      preLoaderRoute: typeof AuthenticatedAkunWishlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/akun/pesanan/': {
      id: '/_authenticated/akun/pesanan/'
      path: '/akun/pesanan'
      fullPath: '/akun/pesanan/'
      preLoaderRoute: typeof AuthenticatedAkunPesananIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin/admin/': {
      id: '/_authenticated/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/akun/pesanan/$id': {
      id: '/_authenticated/akun/pesanan/$id'
      path: '/akun/pesanan/$id'
      fullPath: '/akun/pesanan/$id'
      preLoaderRoute: typeof AuthenticatedAkunPesananIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin/admin/voucher': {
      id: '/_authenticated/_admin/admin/voucher'
      path: '/admin/voucher'
      fullPath: '/admin/voucher'
      preLoaderRoute: typeof AuthenticatedAdminAdminVoucherRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/produk': {
      id: '/_authenticated/_admin/admin/produk'
      path: '/admin/produk'
      fullPath: '/admin/produk'
      preLoaderRoute: typeof AuthenticatedAdminAdminProdukRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/pesanan': {
      id: '/_authenticated/_admin/admin/pesanan'
      path: '/admin/pesanan'
      fullPath: '/admin/pesanan'
      preLoaderRoute: typeof AuthenticatedAdminAdminPesananRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/pengaturan': {
      id: '/_authenticated/_admin/admin/pengaturan'
      path: '/admin/pengaturan'
      fullPath: '/admin/pengaturan'
      preLoaderRoute: typeof AuthenticatedAdminAdminPengaturanRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/pelanggan': {
      id: '/_authenticated/_admin/admin/pelanggan'
      path: '/admin/pelanggan'
      fullPath: '/admin/pelanggan'
      preLoaderRoute: typeof AuthenticatedAdminAdminPelangganRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/audit': {
      id: '/_authenticated/_admin/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/promosi/tema': {
      id: '/_authenticated/_admin/admin/promosi/tema'
      path: '/admin/promosi/tema'
      fullPath: '/admin/promosi/tema'
      preLoaderRoute: typeof AuthenticatedAdminAdminPromosiTemaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/promosi/flash-sale': {
      id: '/_authenticated/_admin/admin/promosi/flash-sale'
      path: '/admin/promosi/flash-sale'
      fullPath: '/admin/promosi/flash-sale'
      preLoaderRoute: typeof AuthenticatedAdminAdminPromosiFlashSaleRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/promosi/dashboard': {
      id: '/_authenticated/_admin/admin/promosi/dashboard'
      path: '/admin/promosi/dashboard'
      fullPath: '/admin/promosi/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminAdminPromosiDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/promosi/ads': {
      id: '/_authenticated/_admin/admin/promosi/ads'
      path: '/admin/promosi/ads'
      fullPath: '/admin/promosi/ads'
      preLoaderRoute: typeof AuthenticatedAdminAdminPromosiAdsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAdminAuditRoute: typeof AuthenticatedAdminAdminAuditRoute
  AuthenticatedAdminAdminPelangganRoute: typeof AuthenticatedAdminAdminPelangganRoute
  AuthenticatedAdminAdminPengaturanRoute: typeof AuthenticatedAdminAdminPengaturanRoute
  AuthenticatedAdminAdminPesananRoute: typeof AuthenticatedAdminAdminPesananRoute
  AuthenticatedAdminAdminProdukRoute: typeof AuthenticatedAdminAdminProdukRoute
  AuthenticatedAdminAdminVoucherRoute: typeof AuthenticatedAdminAdminVoucherRoute
  AuthenticatedAdminAdminIndexRoute: typeof AuthenticatedAdminAdminIndexRoute
  AuthenticatedAdminAdminPromosiAdsRoute: typeof AuthenticatedAdminAdminPromosiAdsRoute
  AuthenticatedAdminAdminPromosiDashboardRoute: typeof AuthenticatedAdminAdminPromosiDashboardRoute
  AuthenticatedAdminAdminPromosiFlashSaleRoute: typeof AuthenticatedAdminAdminPromosiFlashSaleRoute
  AuthenticatedAdminAdminPromosiTemaRoute: typeof AuthenticatedAdminAdminPromosiTemaRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAdminAuditRoute: AuthenticatedAdminAdminAuditRoute,
    AuthenticatedAdminAdminPelangganRoute:
      AuthenticatedAdminAdminPelangganRoute,
    AuthenticatedAdminAdminPengaturanRoute:
      AuthenticatedAdminAdminPengaturanRoute,
    AuthenticatedAdminAdminPesananRoute: AuthenticatedAdminAdminPesananRoute,
    AuthenticatedAdminAdminProdukRoute: AuthenticatedAdminAdminProdukRoute,
    AuthenticatedAdminAdminVoucherRoute: AuthenticatedAdminAdminVoucherRoute,
    AuthenticatedAdminAdminIndexRoute: AuthenticatedAdminAdminIndexRoute,
    AuthenticatedAdminAdminPromosiAdsRoute:
      AuthenticatedAdminAdminPromosiAdsRoute,
    AuthenticatedAdminAdminPromosiDashboardRoute:
      AuthenticatedAdminAdminPromosiDashboardRoute,
    AuthenticatedAdminAdminPromosiFlashSaleRoute:
      AuthenticatedAdminAdminPromosiFlashSaleRoute,
    AuthenticatedAdminAdminPromosiTemaRoute:
      AuthenticatedAdminAdminPromosiTemaRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAkunWishlistRoute: typeof AuthenticatedAkunWishlistRoute
  AuthenticatedAkunPesananIdRoute: typeof AuthenticatedAkunPesananIdRoute
  AuthenticatedAkunPesananIndexRoute: typeof AuthenticatedAkunPesananIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAkunWishlistRoute: AuthenticatedAkunWishlistRoute,
  AuthenticatedAkunPesananIdRoute: AuthenticatedAkunPesananIdRoute,
  AuthenticatedAkunPesananIndexRoute: AuthenticatedAkunPesananIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRoute,
  FaviconDoticoRoute: FaviconDoticoRoute,
  FlashSaleRoute: FlashSaleRoute,
  KatalogRoute: KatalogRoute,
  KeranjangRoute: KeranjangRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VoucherRoute: VoucherRoute,
  ProdukSlugRoute: ProdukSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
